### PR TITLE
Refer to team members instead of CIs

### PR DESCRIPTION
**Pull request by paulajulve**
I'd rather talk about _team members_ than ICs. On one hand, it doesn't need clarification. And on the other, referring to people as "contributors" strips us of a lot of dimensions and facets. We're not just our contributions nor should we strive to be. On that line, I also think it doesn't align really well to the company's values booklet.

Warning: so far I have only reviewed this article. More commits or even more PRs could possibly ensue this one as I keep going XD

### CODE REVIEW

**Comment by franiglesias** [comment]
Totally agreed. Team members or person/people.

**Comment by afontcu** [comment]
I would say "Individual Contributor" is a role such as "Engineering Manager".

From my understading, "IC" means someone who contributes individually – meaning that their path doesn't go through the path of becoming a manager. IC are evaluated from an individual perspective, whereas EM evaluation should take into account the performance (whatever _performance_ means) of the people managed – the ICs. That's the main difference, I'd say.

AFAIK is a quite common term in the industry, not something people at Holaluz came up with.

**Comment by afontcu** [comment]
Also… aren't EM also team members? 🤷

**Comment by franiglesias** [comment]
I don't see the point of IC as a role, I find the term too generic and truly despersonalized. 

Developer, Engineer or Eng. Manager are all roles that can be easily defined in the context of the organization or team. Team member defines a membership relation which embraces both material, social and personal contributions in a way that Individual Contributor doesn't come close from my point of view.

Of course EM are team members, but I think it is easy to interpret the Team Member wording in the context of the document.

Being a common term in the industry doesn't mean that it is a good term at all, specially in the context of a company that wants to be proud of a different way of do things and that wants to keep strong values.

The first time I read the document I had a hard time trying to understand what IC meant. 
I have not managed to feel identified with that word.

**Comment by afontcu** [comment]
> Team member defines a membership relation which embraces both material, social and personal contributions in a way that Individual Contributor doesn't come close from my point of view.

The exact same relationship I would expect from an EM, but they wouldn't be called Team members, would they? That's a bit weird.

> Of course EM are team members, but I think it is easy to interpret the Team Member wording in the context of the document.

What if is out of this document context? Imagine using Team Member in other pages of the Handbook. How easy would it be for people to understand different things out of the same label

> The first time I read the document I had a hard time trying to understand what IC meant.

Can relate to that, but that's on our side (not today, but when I first read about ICs). While there's a lot of literature online, the Handbook should also contain a document explaining the ins and outs of IC, just as they did with the EM.

---

That being said, I'm quite OK with finding a more suitable label if you feel IC do not convey the meaning required to differentiate our role from EMs. What do you call that professional who doesn’t have management responsibilities, who work as an individual and contribute to the goals of the team? I don't think "Team Member" comes any closer.

**Pull request closed without merging**
